// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertBinary(arg1) {
  return window['go']['main']['App']['ConvertBinary'](arg1);
}

export function ConvertHex(arg1) {
  return window['go']['main']['App']['ConvertHex'](arg1);
}

export function ConvertInt(arg1, arg2) {
  return window['go']['main']['App']['ConvertInt'](arg1, arg2);
}
