// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ConvertBinary(arg1:string):Promise<models.ConversionResult>;

export function ConvertFloat(arg1:string,arg2:string):Promise<models.ConversionResult>;

export function ConvertHex(arg1:string):Promise<models.ConversionResult>;

export function ConvertInt(arg1:string,arg2:string):Promise<models.ConversionResult>;

export function ConvertModbusRegisters(arg1:string):Promise<models.ModbusResult>;
