// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertBinary(arg1:string):Promise<main.ConversionResult>;

export function ConvertHex(arg1:string):Promise<main.ConversionResult>;

export function ConvertInt(arg1:string,arg2:string):Promise<main.ConversionResult>;
